name: Build binaries

on:
  push:
  pull_request:

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    name: Build binaries
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Build binaries
        run: make build
